# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-20 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20171020_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='coures_nums',
            new_name='course_nums',
        ),
        migrations.RenameField(
            model_name='courseorg',
            old_name='students_num',
            new_name='student_nums',
        ),
    ]
