# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_teacher_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_nums',
        ),
    ]
